### ISSUE TITLE
UnicodeDecodeError when running app.py

### ISSUE THREAD

**Issue by dennisfurrer** [zishansami102/CNN-from-Scratch#14]
I am using Python 3.7 on MacOS.
I trained the CNN with the MNIST db and tried running app.py
While it starts and I can access it from 127.0.0.1:5000, as soon as I draw a digit and press Predict I get the following console output.

-----------------------------------------------

* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 162-250-119
127.0.0.1 - - [25/Aug/2018 00:29:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2018 00:29:18] "GET /static/style/drawingboard.min.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2018 00:29:18] "GET /static/style/application2.min.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2018 00:29:18] "GET /static/style/drawingBoard.min.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2018 00:29:18] "GET /static/style/hermiteResize.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2018 00:29:23] "POST /digit_process HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dennisfurrer/Desktop/CNN-from-Scratch/app.py", line 23, in digit_process
    out = pickle.load(pickle_in)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 0: ordinal not in range(128)

**Comment by AdityaSoni19031997** [comment]
Ain't sure (not a Mac user) but it seems it's just a codec error specific to MAC..

**Comment by dennisfurrer** [comment]
Any ideas on how to fix it? @AdityaSoni19031997

**Comment by AdityaSoni19031997** [comment]
If we are lucky, then it should be solved by passing in the encoding parameter while opening that pickle file or try to include this on the top of that file"# -- coding: utf-8 --" or check this discussion https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by dennisfurrer** [comment]
Could you clarify which file you mean? I assumed it was the trained.pickle file but that resulted in an error " _pickle.UnpicklingError: invalid load key, '#'. "

Thank you in advance for your help @AdityaSoni19031997

**Comment by AdityaSoni19031997** [comment]
It has been quite a while since I ran the code.. but the last line of the traceback where we are opening the pickle file, we might change the encoding...

If nothing works, then we can comment out the flask part maybe !
I am out of ideas as of now..(Sorry for that)

**Comment by dennisfurrer** [comment]
You mean by adding the encoding type to replace this:

pickle_in = open(PICKLE_FILE, 'rb')

with this:

pickle_in = open(PICKLE_FILE, 'rb', "encoding=utf-8")

?

Then I get the following error: " ValueError: binary mode doesn't take an encoding argument "

**Comment by AdityaSoni19031997** [comment]
Why the rb, only r should do ? 
PS I ain't sure but for me it's was always the encoding parameter which I mess up, so fixing that fixes stuff for me..

**Comment by AdityaSoni19031997** [comment]
pickle_in = open(PICKLE_FILE, 'r', encoding='utf-8');

**Comment by dennisfurrer** [comment]
thats the code thats on this repository? I'll try replacing it with 'r'

**Comment by dennisfurrer** [comment]
I now get " TypeError: a bytes-like object is required, not 'str' "

**Comment by nitinseven** [comment]
same error I also got on windows with python 3.5
UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 0: ordinal not in range(128)

any solution?

**Comment by yanatarkhaeva** [comment]
I assume the solution is to train this network on your Python 3.x and then save the result using pickle (the pickle which is for the third version of Python). So when you'll predict it would unpack the file which is saved by the same module. But this will take approximately 80 hours (on my not-so-powerfull laptop). That's the thing I'm now struggling on. Because I need to learn a neural network of this type by the next day and it's still 50 hours remaining. So if someone has an opportunity to train the network on MNIST dataset faster then me, share the resulting output.pickle file here, please.
(English isn't my first language sorry if I made mistakes.)

**Comment by dennisfurrer** [comment]
Hope this helps @yanatarkhaeva 
https://github.com/dennisfurrer/cnn-output-pickle

**Comment by AdityaSoni19031997** [comment]
You can use kaggle kernels/Colab/free GPU to train

**Comment by AdityaSoni19031997** [comment]
Bytes like object might mean the way we are opening or creating or passing the file name isn't correct ...
Happened with me few days back
