### ISSUE TITLE
Add : Flask API for Digit Recognizer

### ISSUE THREAD

**Issue by zishansami102** [zishansami102/CNN-from-Scratch#4]
## Description:
An API which receives image as input and gives digit prediction and its probability for that image as output(from functions available in 'convnet.py' file).
Use 'app.py' file to start from.
[read the README for more details]

**Comment by phaniavi** [comment]
Hello Sir,
I am interested in this part of the project, and would like to contribute.

**Comment by zishansami102** [comment]
@phaniavi 
Great !! Then i am assigning this task to you. You can start working on this(look app.py file for reference).
If you have any doubts about anything post it in the google group.
And please don't call me sir, as currently i am also a student.

**Comment by zishansami102** [comment]
@phaniavi 
if you have started the work or going to do so then please post about it in the [google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/cnn-from-scratch) so that others can see who is currently working on what!! There may me more than one contributor on this issue or any other.

**Comment by AdityaSoni19031997** [comment]
Trying to get this one done..
How to deploy on github/horeku(spelling might be wrong)?

**Comment by zishansami102** [comment]
No need to do it.
Work is almost done. Just need to update.

**Comment by AdityaSoni19031997** [comment]
But still I will try..

**Comment by zishansami102** [comment]
Done
